---
metadataformat: "yaml"
title: "aurelienberra.org"
baseurl: "https://aurelienberra.org"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
canonifyurls: true
taxonomies:
  category: "categories"
pluralizelisttitles: "false"
defaultcontentlanguage: "fr"
blackfriday:
  smartypants: true
  smartypantsQuotesNBSP: true
  angledQuotes: true
footnotereturnlinkcontents: "⌃"
permalinks:
  blog: /blog/:year/:month/:title/
menu:
  main:
      - name: "CV"
        url: "/cv"
        weight: 1
      - name: "Publications"
        url: "/publications"
        weight: 2
      - name: "Enseignement"
        url: "/enseignement"
        weight: 3
      - name: "Blog"
        url: "/blog"
        weight: 4
      - name: "XXX"
        url: "/xxx"
        weight: 5
...
