---
metadataformat: "yaml"
title: "Aurélien Berra"
baseurl: "https://aurelberra.github.io"
# baseurl: "https://aurelienberra.org"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true # check
canonifyurls: true
indexes:
  category: "categories"
pluralizelisttitles: "false"
defaultcontentlanguage: "fr"
# blackfriday:
#   angledQuotes: true
menu:
  main:
      - Name: "Curriculum vitæ"
        URL: "/cv"
        Weight: 1
      - Name: "Publications"
        URL: "/publications" # writing
        Weight: 2
#      - Name: "Interventions"
#        URL: "/interventions" # talks
#        Weight: 3
      - Name: "Enseignement"
        URL: "/enseignement" # teaching
        Weight: 3
      - Name: "Blog"
        URL: "/blog"
        Weight: 4
...
