---
metadataformat: "yaml"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true # check
baseurl: "https://aurelberra.github.io"
# baseurl: "https://aurelienberra.org"
indexes:
  category: "categories"
title: "Aurélien Berra"
canonifyurls: true
# blackfriday:
#   angledQuotes: true
...
