---
metadataformat: "yaml"
title: "Aurélien Berra"
baseurl: "https://aurelberra.github.io"
# baseurl: "https://aurelienberra.org"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true # check
canonifyurls: true
indexes:
  category: "categories"
pluralizelisttitles: "false"
# blackfriday:
#   angledQuotes: true
...
