---
metadataformat: "yaml"
title: "aurelienberra.org" # Aurélien Berra
baseurl: "https://aurelienberra.org"
# baseurl: "http://aurelienberra.org"
# baseurl: "https://aurelberra.github.io"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true # check
canonifyurls: true
indexes:
  category: "categories"
pluralizelisttitles: "false"
defaultcontentlanguage: "fr"
blackfriday:
  smartypants: true
  smartypantsQuotesNBSP: true
  angledQuotes: true
footnotereturnlinkcontents: "⌃" # ↩ ↵ ⤣ ↑ ⇧ ☝︎ ↺ ▲ ^
permalinks:
  blog: /blog/:year/:month/:title/
menu:
  main:
      - Name: "CV"
        URL: "/cv"
        Weight: 1
      - Name: "Publications"
        URL: "/publications" # writing
        Weight: 2
#      - Name: "Interventions"
#        URL: "/interventions" # talks
#        Weight: 3
      - Name: "Enseignement"
        URL: "/enseignement" # teaching
        Weight: 3
      - Name: "Blog"
        URL: "/blog"
        Weight: 4
      - Name: "XXX"
        URL: "/xxx"
        Weight: 5
...
